CREATE TABLE IF NOT EXISTS staging_submissions (
    "archived" boolean,
    "author" varchar(max),
    "author_created_utc" int,
    "author_fullname" varchar(max),
    "can_gild" boolean,
    "can_mod_post" boolean,
    "category" varchar(max),
    "contest_mode" boolean,
    "created_utc" int,
    "discussion_type" varchar(max),
    "domain" varchar(max),
    "edited" varchar(max),  -- dangerous column, can be either boolean or a timestamp
    "event_end" int,
    "event_is_live" boolean,
    "event_start" int,
    "gilded" int,
    "hidden" boolean,
    "id" varchar(max),
    "is_crosspostable" boolean,
    "is_meta" boolean,
    "is_original_content" boolean,
    "is_reddit_media_domain" boolean,
    "is_robot_indexable" boolean,
    "is_self" boolean,
    "is_video" boolean,
    "locked" boolean,
    "no_follow" boolean,
    "num_comments" int,
    "num_crossposts" int,
    "over_18" boolean,
    "permalink" varchar(max),
    "pinned" boolean,
    "post_hint" varchar(max),
    "quarantine" boolean,
    "removal_reason" varchar(max),
    "retrieved_on" int,
    "score" int,
    "selftext" varchar(max),
    "spoiler" boolean,
    "stickied" boolean,
    "subreddit" varchar(max),
    "subreddit_id" varchar(max),
    "subreddit_name_prefixed" varchar(max),
    "subreddit_subscribers" int,
    "subreddit_type" varchar(max),
    "suggested_sort" varchar(max),
    "thumbnail" varchar(max),
    "thumbnail_height" int,
    "thumbnail_width" int,
    "title" varchar(max),
    "total_awards_received" int,
    "url" varchar(max),
    "whitelist_status" varchar(max)
);

CREATE TABLE IF NOT EXISTS staging_subreddits (
  "accounts_active" int,
  "accounts_active_is_fuzzed" boolean,
  "active_user_count" int,
  "advertiser_category" varchar(max),
  "all_original_content" boolean,
  "allow_discovery" boolean,
  "allow_images" boolean,
  "allow_videogifs" boolean,
  "allow_videos" boolean,
  "banner_background_color" varchar(max),
  "banner_background_image" varchar(max),
  "banner_img" varchar(max),
  "banner_size" varchar(max),   -- dangerous column, either null or an array of two numbers
  "can_assign_link_flair" boolean,
  "can_assign_user_flair" boolean,
  "collapse_deleted_comments" boolean,
  "comment_score_hide_mins" int,
  "community_icon" varchar(max),
  "created_utc" int,
  "description" varchar(max),
  "display_name" varchar(max),
  "display_name_prefixed" varchar(max),
  "emojis_custom_size" varchar(max), -- dangerous column, either null or an array of two numbers
  "emojis_enabled" boolean,
  "free_form_reports" boolean,
  "has_menu_widget" boolean,
  "header_img" varchar(max),
  "header_size" varchar(max),
  "header_title" varchar(max),
  "hide_ads" boolean,
  "icon_img" varchar(max),
  "icon_size" varchar(max),
  "id" varchar(max),
  "is_enrolled_in_new_modmail" boolean,
  "key_color" varchar(max),
  "lang" text,
  "link_flair_enabled" boolean,
  "link_flair_position" varchar(max),
  "name" varchar(max),
  "notification_level" text,
  "original_content_tag_enabled" boolean,
  "over18" boolean,
  "primary_color" text,
  "public_description" varchar(max),
  "public_traffic" boolean,
  "quarantine" boolean,
  "retrieved_on" int,
  "show_media" boolean,
  "show_media_preview" boolean,
  "spoilers_enabled" boolean,
  "submission_type" text,
  "submit_link_label" varchar(max),
  "submit_text" varchar(max),
  "submit_text_label" varchar(max),
  "subreddit_type" text,
  "subscribers" int,
  "suggested_comment_sort" text,  -- unclear
  "title" varchar(max),
  "url" varchar(max),
  "videostream_links_count" int,
  "whitelist_status" text,
  "wiki_enabled" boolean,
  "wls" int
);

CREATE TABLE IF NOT EXISTS staging_authors (
  "id" bigint,
  "author" varchar(max),
  "created" int,
  "last_login" int,
  "karma_posts" int,
  "karma_comments" int,
  "author_valid" int
);

CREATE TABLE IF NOT EXISTS staging_times (
  "start_time" timestamp NOT NULL
);